// <auto-generated />
using System;
using Distro.Infra.Data.Context;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Distro.Infra.Data.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20260111225701_Inicial")]
    partial class Inicial
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.1")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Distro.Domain.Entities.Category", b =>
                {
                    b.Property<Guid>("CategoryId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("CategoryId");

                    b.ToTable("Categories");

                    b.HasData(
                        new
                        {
                            CategoryId = new Guid("a1b2c3d4-e5f6-4789-9012-abcdefabcdef"),
                            Name = "Customizaveis"
                        },
                        new
                        {
                            CategoryId = new Guid("b2c3d4e5-f678-4901-2345-bcdefabcdefa"),
                            Name = "Privacidade"
                        },
                        new
                        {
                            CategoryId = new Guid("89012345-6789-4678-9012-bcdefabcdefa"),
                            Name = "Educacional"
                        },
                        new
                        {
                            CategoryId = new Guid("90123456-7890-4789-0123-cdefabcdefab"),
                            Name = "Desenvolvimento"
                        });
                });

            modelBuilder.Entity("Distro.Domain.Entities.Distro", b =>
                {
                    b.Property<Guid>("DistroId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("CategoryId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Descricao")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<string>("ImageUrl")
                        .IsRequired()
                        .HasMaxLength(250)
                        .HasColumnType("nvarchar(250)");

                    b.Property<string>("Iso")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("DistroId");

                    b.HasIndex("CategoryId");

                    b.ToTable("Distros", (string)null);
                });

            modelBuilder.Entity("Distro.Domain.Entities.Distro", b =>
                {
                    b.HasOne("Distro.Domain.Entities.Category", "Category")
                        .WithMany("Distros")
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Category");
                });

            modelBuilder.Entity("Distro.Domain.Entities.Category", b =>
                {
                    b.Navigation("Distros");
                });
#pragma warning restore 612, 618
        }
    }
}
